mutation CreateMessage($content: String!, $conversationId: ID!) {
  messageId: createMessage(content: $content, conversationId: $conversationId)
}

mutation LoginUser($conversationName: String, $username: String!) {
  userConversation: loginUser(
    conversationName: $conversationName
    username: $username
  ) {
    conversation {
      id
    }
    user {
      id
    }
  }
}
